CREATE USER 'monitralldbbare'@'localhost' IDENTIFIED BY  'Passw0rd';

GRANT USAGE ON * . * TO  'monitralldbbare'@'localhost' IDENTIFIED BY  'Passw0rd' WITH MAX_QUERIES_PER_HOUR 0 MAX_CONNECTIONS_PER_HOUR 0 MAX_UPDATES_PER_HOUR 0 MAX_USER_CONNECTIONS 0 ;

CREATE DATABASE IF NOT EXISTS  `monitralldbbare` ;